### ISSUE TITLE
Improve release notes [4h]

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-starter#172]
# Desired format

## Release 1.11

 - Issue one (#11111)
     - Pull request one (#22222)
     - Pull request two (#444444)
 - Issue Two (#999999)
    - Pull request (#1234567)

Contributors:
 - User1
 - User2
 - User3

(authors of the issues and the pull requests enumerated above)

# Technical notes

It will mean that the release notes script will require a personal access token to GitHub to gather all this information. I can save it locally to avoid to enter it again and again

**Comment by AronNovak** [comment]
^^ @isapisa any requests for the output?

**Comment by isapisa** [comment]
@AronNovak I wonder if the above format is necessary due to the current output of referenced issues and pull request that github already do out of the box now. Otherwise, I like it

**Comment by AronNovak** [comment]
> github already do out of the box now

Hm, maybe I am not aware of something, let me check.

**Comment by AronNovak** [comment]
@isapisa The current release notes at client projects are not from GitHub, but generated by a Robo script that we developed. The idea is to improve it to have the issue titles too and group the pull requests by issues.

**Comment by isapisa** [comment]
this is what I mean:

https://github.com/Gizra/undg-country/issues/3447#issuecomment-866096836

<img width="867" alt="Screenshot 2021-07-06 at 08 33 34" src="https://user-images.githubusercontent.com/34378755/124553340-e82f1f00-de34-11eb-8ea2-d1d1f30e7514.png">

**Comment by AronNovak** [comment]
@isapisa Are you sure that it's not Mariano crafted by hand?

**Comment by isapisa** [comment]
@AronNovak no, this was out of the box. Maybe github tested this for some users and it looks like now it's no longer a feature anymore.

**Comment by AronNovak** [comment]
Yep. But the release notes for that version looks different: https://github.com/Gizra/undg-country/releases/tag/1.22.1
So it's still a bit strange, anyways, I go ahead to improve what we have.

**Comment by isapisa** [comment]
@AronNovak yep, just FYI, this is what we had to do because of that feature: https://github.com/Gizra/unsdg/releases/tag/2.4.0

But maybe everyone got annoyed at it and they rolled it back :D
