### ISSUE TITLE
Replace Homepage Controller with Landing page + Paragraphs [4h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#189]
https://github.com/Gizra/drupal-starter/blob/f40ef9df2a8b279ffb412b178f1b5f9934ee6e99/web/modules/custom/server_general/src/Controller/Homepage.php

## Task

1. Add content type "Landing page"
2. Add Paragraph type "Views" with a field "field_views" which is a select list with hand picked Views.
3. Migrate a Homepage node, and set it in config to the the site's home page

**Comment by andreytroeglazov** [comment]
Done.

**Comment by amitaibu** [comment]
Thanks
