### ISSUE TITLE
Theme is very slow to compile

### ISSUE THREAD

**Issue by bmunslow** [Gizra/drupal-starter#204]
First up, thank you for sharing the development of this project, it's brilliant.

On a fresh `gizra/drupal-starter` DDEV installation, the `ddev robo theme:compile-debug` command takes about **30 seconds** to complete. This feels very slow when working on frontend tasks.

The same happens when using the `ddev robo theme:watch-debug` command, which basically invokes the `theme:compile-debug` on every change.

The Just-In-Time Mode from Tailwind, however, [advertises](https://tailwindcss.com/docs/just-in-time-mode) _lightning fast build times... even the biggest projects in about 800ms_, so I was wondering what could be done to speed it up (or whether it's ultra fast for everyone else and this is just an issue with my setup, I use a Macbook).

For starters, we could shave off about 5 seconds by removing the `drush cache:rebuild`, since Twig and Drupal caching are often disabled anyway during development.

![image](https://user-images.githubusercontent.com/295192/136745250-1767e895-1046-4342-b852-ec194b22cd47.png)

**Comment by amitaibu** [comment]
Yeah, commands have shifted a bit. Happy you are enjoy the starter :smile:
