### ISSUE TITLE
Put the theme on drupal.org

### ISSUE THREAD

**Issue by AronNovak** [Gizra/drupal-starter#232]
It might be interesting, as Tailwind is relatively new, it might be a publicly available base tailwind theme.

**Comment by AronNovak** [comment]
^^ @amitaibu What do you think?

**Comment by amitaibu** [comment]
Thanks, but I'm going to won't fix this. I think it would make dev a bit harder, and the value won't be enough.

People can use https://www.drupal.org/project/tailwindcss , if they like it :smile: 

I think the biggest gain in Drupal-starter isn't the theme itself, but rather how it plays nicely with the tooling, config and PEVB
