### ISSUE TITLE
Set homepage after migration

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#259]
## Issue

Upon clean installation we set the homepage to be `/homepage` on `/admin/config/system/site-information` . But if we check `\Drupal::service('path.matcher')->isFrontPage();` it will return False. If we then manually change the URL and then back to `/homepage` and click save, then under the hood it changes it to the internal path (e.g. /node/21).  

![Selection_999(1065)](https://user-images.githubusercontent.com/125707/170026708-ce8f61b1-1a55-4c07-93fb-561d7c356cc2.jpg)

## Task

1. Confirm my findings
2. Instead of setting it via config, after the migration is executed, we can set it.

**Comment by bboro** [comment]
> Confirm my findings

Yep that's correct. It also keeps forwarding the user to `/homepage` instead of `/` when you go to the root.

> Instead of setting it via config, after the migration is executed, we can set it.

Assume automatically and not manually? I also think we should ignore this configuration so people can freely change this on other environments such as live, qa etc.
