### ISSUE TITLE
Configure ddev and add an example of JavascriptTests

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#307]
We could use this guide https://mglaman.dev/blog/running-drupals-functionaljavascript-tests-ddev to include an example of how to create a JavascriptTest that could help us remove wdio tests from other projects.

**Comment by amitaibu** [comment]
We got too many false positives with JS testing in the past, which I really don't miss :)

So I'd say either convert some of the tests to the `ExistingSite` testing, or get rid of them. Usually their value is low, and maintaince cost is high.

So going to won't fix this.

**Comment by bboro** [comment]
Reopening to propose to introduce https://github.com/ddev/ddev-selenium-standalone-chrome so we can have at least an option to quickly implement JS tests when needed

**Comment by bboro** [comment]
> So I'd say either convert some of the tests to the `ExistingSite` testing

We're still using `ExistingSite` for the new JS tests :tada: , PR is open for review.
