### ISSUE TITLE
Prevent deletion/ unpublish of "locked" landing pages [3h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#308]
## Issue

We want to prevent a content editor from accidentally deleting for example the homepage, or any other important Landing page. Also setting it to unpublished would not be good. 
My idea is to have some settings page, where site admin can reference Landing page nodes. Once referenced those node could not be deleted or unpublish.

## Task

1. Use [Config pages](https://www.drupal.org/project/config_pages) module to setup the admin page :smile: 
2. Prevent delete on hook_node_delete
3. Prevent unpublish on hook_node_presave
4. Remove delete/ unpublish options from UI
5. Add drupal_set_message indicating this is a "Locked" Landing page

**Comment by GizraNotifier** [comment]
The site could not be fully updated at Pantheon at qa. Try fixing manually.
