### ISSUE TITLE
Mention the tag name in pantheon deployments

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#334]
@AronNovak I think it should be possible to indicate the tag name when deploying, no? I will add more information about the latest deployed tag in production for any project.

![Screenshot_2022-10-05_15-40-45](https://user-images.githubusercontent.com/5313631/194137474-ab6f5360-56df-4de3-ae8b-350620d81ca8.png)

**Comment by AronNovak** [comment]
@mariano-dagostino It depends on the Robo command we use.
https://github.com/Gizra/drupal-starter/blob/main/RoboFile.php#L244 - see this.
However I added a bit more robustness in https://github.com/Gizra/drupal-starter/pull/365/files

**Comment by amitaibu** [comment]
Can be closed?

**Comment by AronNovak** [comment]
Yep.
