### ISSUE TITLE
Remove entity browser and rely on media library

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#354]
Media Library seems a more user friendly way to upload images

## Currently using entity browser

https://user-images.githubusercontent.com/5313631/198107474-313e30e5-2044-46a0-8e69-8eaa12702cca.mp4

## Proposed

https://user-images.githubusercontent.com/5313631/198107491-1e5cf46b-f61b-4606-9e62-ad2f7e626e10.mp4

**Comment by amitaibu** [comment]
I do not see too many differences in the video - can you give the pros?
I guess you can you upload new images with media library, but didn't see in the video how it looks

**Comment by mariano-dagostino** [comment]
> I do not see too many differences in the video - can you give the pros?

Media library does not allows you to choose multiple items in single entry media values. See how all images are unchecked when you select one.

Here is the UI to upload new images:

https://user-images.githubusercontent.com/5313631/198108463-8fc9d794-6f8f-4ae3-bef8-dadacee58651.mp4

**Comment by amitaibu** [comment]
I'm ok with doing the switch. @bboro ?

**Comment by mariano-dagostino** [comment]
Also, we are already using this for News.

![Screenshot_2022-10-26_15-40-49](https://user-images.githubusercontent.com/5313631/198109559-c4228521-88ba-48c0-b8b1-4908db458fa4.png)

**Comment by bboro** [comment]
Yeah fine with me :+1:

**Comment by mariano-dagostino** [comment]
Done in https://github.com/Gizra/drupal-starter/pull/355
