### ISSUE TITLE
Wrong commit message on the Pantheon repo

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#364]
![image](https://user-images.githubusercontent.com/125707/201866116-b6f764a3-edfc-4361-b1cc-e73504e0ea8a.png)

**Comment by AronNovak** [comment]
Partially duplicate of https://github.com/Gizra/drupal-starter/issues/334
Also not every client project has this broken status, it seems we just need to port the fix to Starter, if it"s broken there.
