### ISSUE TITLE
Config warning on PEVB upon installation

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#374]
![image](https://user-images.githubusercontent.com/125707/203857459-70b96d76-8fe6-407d-b2da-85f43c7751b2.png)

@bboro I remember we fixed it in the past, but seems we still have something here.

**Comment by GizraNotifier** [comment]
The latest merged PR just got deployed successfully to Pantheon [`qa`](https://gizra-drupal-starter-qa.pantheonsite.io) environment
