### ISSUE TITLE
Create `demo` site with Drupal starter [2h]

### ISSUE THREAD

**Issue by nora-novak** [Gizra/drupal-starter#427]
### Issue
Isa and I need to know what is available in the drupal starter, what are the default values in theming, etc. and the easiest way to check this if we spin up a Pantheon server running Drupal-starter.

### To Do
^^

**Comment by AronNovak** [comment]
@nora-novak this is near completion.

http://qa-gizra-drupal-starter.pantheonsite.io/
http://dev-gizra-drupal-starter.pantheonsite.io/

Should we have ElasticSearch as well? It's a paid thing. @amitaibu Possibly on the docker mirror, a small ES instance would fit in.

**Comment by nora-novak** [comment]
@AronNovak I don't think ES is needed, this is mainly for Isa and I to check what CTs, para types, etc. we have in the drupal-starter.

**Comment by amitaibu** [comment]
1. No need for ES.
2. Let's run migrate so the homepage is populated.
3. @nora-novak you can see the style guide under https://qa-gizra-drupal-starter.pantheonsite.io/style-guide

**Comment by AronNovak** [comment]
@amitaibu 
![image](https://user-images.githubusercontent.com/114076/218057863-05056af2-9b96-44c9-b3d3-cf170b6fc3ce.png)

We did a full-blown setup, inlcuding migration both on QA and DEV.
Something else is missing then, I'll look around.

Also I will wire autodeploy, for the public GH repository, I have some issues with Travis CLI

**Comment by AronNovak** [comment]
The homepage is sorted out: https://github.com/Gizra/drupal-starter/pull/428/commits/b8e62ad3f3f19cd7171861157e7bb804c95ffa56#diff-3509ac863f41a4b2c6e5f60636671c3793aa7289ade00863eb8b4a24254bfdd1R399

**Comment by AronNovak** [comment]
Right now Spanish has all Arabic translations, will fix it in https://github.com/Gizra/drupal-starter/pull/428 as well

**Comment by GizraNotifier** [comment]
The latest merged PR #433 just got deployed successfully to Pantheon [`qa`](https://qa-gizra-drupal-starter.pantheonsite.io/) environment

**Comment by AronNovak** [comment]
@nora-novak @isapisa Do you need anything else here? The site is ready to use.

**Comment by isapisa** [comment]
@AronNovak could we get a login?

**Comment by AronNovak** [comment]
@isapisa Yep, but I can't put it in the Wiki... :lock:

**Comment by isapisa** [comment]
@AronNovak got it, thanks

**Comment by nora-novak** [comment]
@AronNovak I have everything that I need
