### ISSUE TITLE
Config not clean after clean installation [2h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#447]
The Arabic/ Spanish issue is still around.

![image](https://user-images.githubusercontent.com/125707/223414303-8ddc60ef-1742-4387-9622-3f3eb6c61a1f.png)

**Comment by GizraNotifier** [comment]
The latest merged PR #471 just got deployed successfully to Pantheon [`qa`](https://gizra-drupal-starter-qa.pantheonsite.io) environment
