### ISSUE TITLE
Improve release notes doc

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#467]
https://github.com/Gizra/drupal-starter#release-notes

1. Let's specify which permissions are needed for the personal access token
2. Let's add the "two new environment variables" to [config.local.yaml.example](https://github.com/Gizra/drupal-starter/blob/b9de5356a8572a866718c2bb70db7d711ae1bfa6/.ddev/config.local.yaml.example)

**Comment by GizraNotifier** [comment]
The latest merged PR #484 just got deployed successfully to Pantheon [`qa`](https://gizra-drupal-starter-qa.pantheonsite.io) environment
