### ISSUE TITLE
Use `default_content` module for installation content [4h]

### ISSUE THREAD

**Issue by bboro** [Gizra/drupal-starter#514]
Use [`default_content`](https://www.drupal.org/project/default_content) for easier management of content on-install.

- Install and configure `default_content`
- Move `migrate` default content to `default_content` module's yml exports
  - I'm thinking it's best to move it to a dedicated module `server_default_content`, so we can disable/enable without having to worry about dependencies
- Update documentations on workflow on how to export/update/import the content

**Comment by GizraNotifier** [comment]
The latest merged PR just got deployed successfully to Pantheon [`qa`](https://gizra-drupal-starter-qa.pantheonsite.io) environment

**Comment by bboro** [comment]
@amitaibu closing issue as this is now done.
