### ISSUE TITLE
Fix wrong background-repeat on Status messages [1h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#553]
1. Create a node
1. See the status message:

<img width="1351" alt="image" src="https://github.com/Gizra/drupal-starter/assets/125707/af1f915d-8d2a-4a31-bfce-5810e37b90df">

**Comment by GizraNotifier** [comment]
The latest merged PR #556 just got deployed successfully to Pantheon [`qa`](https://gizra-drupal-starter-qa.pantheonsite.io) environment
