### ISSUE TITLE
Element: Info cards -  Center headers spanning multiple lines

### ISSUE THREAD

**Issue by bmunslow** [Gizra/drupal-starter#566]
Info cards look great when the title takes up a single line. However, if the title spans on several lines, it's aligned to the left but I think it should be centered.

**Desktop:**
![image](https://github.com/Gizra/drupal-starter/assets/295192/8ddcdd4a-3de6-459a-87ca-5b2864cd854a)

**Mobile:**
![image](https://github.com/Gizra/drupal-starter/assets/295192/d85f4ff1-4d8e-484e-8a9c-406e1c21a434)

**Comment by amitaibu** [comment]
> it's aligned to the left but I think it should be centered.

I agree - it should be centered.

**Comment by GizraNotifier** [comment]
The latest merged PR #567 just got deployed successfully to Pantheon [`qa`](https://qa-gizra-drupal-starter.pantheonsite.io) environment
