### ISSUE TITLE
Add JS test(s) [2h]

### ISSUE THREAD

**Issue by isapisa** [Gizra/drupal-starter#586]
### Issue

> Would be great to have something in Drupal starter which shows a dev what the test is actually doing in a browser

// @amitaibu

**Comment by bboro** [comment]
PR Opened #600

**Comment by bboro** [comment]
@isapisa @amitaibu this is now done.

**Comment by isapisa** [comment]
@bboro let the devs know?

**Comment by GizraNotifier** [comment]
The site could not be fully updated at Pantheon at qa. Try fixing manually.
