### ISSUE TITLE
Travis build should fail whenever theme compilation fails

### ISSUE THREAD

**Issue by ordavidil** [Gizra/drupal-starter#61]
@AronNovak 
As of now, compiling the theme may fail, but travis still pass:
![image](https://user-images.githubusercontent.com/5985683/91969232-b4173900-ed0d-11ea-8952-f577418db9d8.png)

//cc @amitaibu

**Comment by AronNovak** [comment]
![image](https://user-images.githubusercontent.com/114076/94688389-d6f93500-032d-11eb-9ee0-8f670a3f68d3.png)
The big issue is that `ddev start` swallows the exit code, even if i put `exit 1` in config.yaml, I have no feedback about it afterwards. I'll check how we can handle it still.

**Comment by AronNovak** [comment]
https://github.com/drud/ddev/issues/2536
