### ISSUE TITLE
Give Elements better names, and seperate into better named traits [6h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#614]
Right now, we have many elements crammed together under a few traits.

For example, https://github.com/Gizra/drupal-starter/blob/0069ac59f6d88f73fc77021032723c56d227144d/web/modules/custom/server_general/src/ElementTrait.php#L169 lives under `ElementTrait.php,` but could happily live in `CarouselTrait.php`

This one https://github.com/Gizra/drupal-starter/blob/0069ac59f6d88f73fc77021032723c56d227144d/web/modules/custom/server_general/src/ElementTrait.php#L248 can live under `NewsTrait.php` (or `TeaserTrait`?)

In other words, we need to keep the functionality but reduce the abstractions of the names.

So it's not just a matter of dev, but also some dev psychology -- "where would another dev be looking for this element"?

- [ElementTrait.php](https://github.com/Gizra/drupal-starter/blob/0069ac59f6d88f73fc77021032723c56d227144d/web/modules/custom/server_general/src/ElementTrait.php)
- [InnerElementTrait.php](https://github.com/Gizra/drupal-starter/blob/0069ac59f6d88f73fc77021032723c56d227144d/web/modules/custom/server_general/src/InnerElementTrait.php)
- ... and maybe other traits would benefit from this

**Comment by bboro** [comment]
@amitaibu this is now done I suppose. And can be closed if you want to.

**Comment by GizraNotifier** [comment]
The site could not be fully updated at Pantheon at qa. Try fixing manually.
