### ISSUE TITLE
Add caching to hook_entity_access()

### ISSUE THREAD

**Issue by balagan73** [Gizra/drupal-starter#626]
We could add caching based on the ConfigPages entity used to store locked nodes.

**Comment by amitaibu** [comment]
I'm not sure `hook_entity_access` uses caching.

**Comment by balagan73** [comment]
We have an Access checker in hook_entity_access(), and I am acting based on https://www.drupal.org/docs/8/api/cache-api/access-checkers-cacheability

**Comment by GizraNotifier** [comment]
The site could not be fully updated at Pantheon at qa. Try fixing manually.
