### ISSUE TITLE
Decide if security_review should be included or not as part of Drupal Starter

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#632]
UI version

![Screenshot 2024-03-01 at 14-31-25 Drupal Starter](https://github.com/Gizra/drupal-starter/assets/5313631/730f7b33-ab91-438d-ba27-81e9c658e655)

Drush version

![Screenshot_2024-03-01_14-30-26](https://github.com/Gizra/drupal-starter/assets/5313631/37ef722e-07aa-4f70-82c2-31d11f5a3fc8)

Note: The private_files check fails with a fatal error:

![Screenshot_2024-03-01_14-10-12](https://github.com/Gizra/drupal-starter/assets/5313631/46a22d13-6de2-4dab-ba42-352030519240)

**Comment by amitaibu** [comment]
I think it's a nice addition. What are your thoughts?

**Comment by amitaibu** [comment]
Thanks. Ok, let's not include then - closing
