### ISSUE TITLE
Fix Dynamic Page Caching

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#638]
There is something preventing Dynamic Page Cache working on the homepage and any page of drupal-starter.

![Screenshot_2024-03-07_15-21](https://github.com/Gizra/drupal-starter/assets/5313631/9cdc4b53-becf-47b5-9a07-1d84d57e65ac)

**Comment by GizraNotifier** [comment]
The site could not be fully updated at Pantheon at qa. Try fixing manually.
