### ISSUE TITLE
Enable Content moderation [2h]

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#647]
States:

- Draft
- Review
- Published

For role:

- Editor

**Comment by balagan73** [comment]
@amitaibu Don't we need an 'Unpublished' state? I guess 'Review' should be called 'Ready for review'.

**Comment by amitaibu** [comment]
Sure, go ahead

**Comment by GizraNotifier** [comment]
The site could not be fully updated at Pantheon at qa. Try fixing manually.
