### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#669]
https://app.travis-ci.com/github/Gizra/drupal-starter/jobs/622009499#L2395

I think we can remove the sync to QA, I don't think we've used it anytime in the past couple of years

**Comment by amitaibu** [comment]
@AronNovak ^^

**Comment by AronNovak** [comment]
@amitaibu As we merge deploy-related code too to Drupal Starter, I'd rather execute the deploy code, but allow to fail, that's #686 , or we can completely clean it up in #685 .
