### ISSUE TITLE
Improve first time project setup with travis and pantheon

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#700]
Few notes I observed during a fresh pantheon install:

1. https://github.com/Gizra/drupal-starter?tab=readme-ov-file#pantheon-setup it seems it is not necessary to change anything here as the autoconfig does replacements.
2. The bootstrap already installs the site, so https://github.com/Gizra/drupal-starter?tab=readme-ov-file#create-your-site can be marked as optional or at least add a note this is not required.
3. The bootstrap should call to https://github.com/Gizra/drupal-starter?tab=readme-ov-file#automatic-deployment-to-pantheon or at least suggest it as a next step.
4. The automatic deployment failed to define the `PANTHEON_GIT_URL` on .travis.yml this leads to a weird error `fatal: the empty string is not a valid path` maybe a check in prepare_deploy.sh to be more verbose about when this is missing.
5. Only `terminus_token` is encrypted in prepare autodeploy, the `github_token` is not encrypted but is required to send notifications.

**Comment by amitaibu** [comment]
Good points, thanks!

Would you be able to tackle them? :smiley:
