### ISSUE TITLE
Replace Twitter icon [1h]

### ISSUE THREAD

**Issue by isapisa** [Gizra/drupal-starter#718]
### Issue

We should replace the twitter icon with the X icon: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

https://gizra:1234@dev-gizra-drupal-starter.pantheonsite.io/news/current-digital-marketing-sports-watching-rather-marketing

<img width="1374" alt="Screenshot 2024-09-16 at 14 50 23" src="https://github.com/user-attachments/assets/73c99b73-f6cb-476a-893c-33d603f8ab8a">

### To Do

- Replace Twitter icon

**Comment by balagan73** [comment]
@isapisa Should I also modify the hover text to Share on X?
![image](https://github.com/user-attachments/assets/8b60528e-330b-49ca-87fc-776027f90629)

**Comment by isapisa** [comment]
@balagan73 yes please

**Comment by sonvir249** [comment]
@amitaibu this seems to be fixed. Can we close this issue?
Current twitter icon:
![image](https://github.com/user-attachments/assets/8fe4ad33-2677-4f9e-9e4e-c2f97b70a2cf)
