### ISSUE TITLE
Theming the default contact form [3h]

### ISSUE THREAD

**Issue by isapisa** [Gizra/drupal-starter#726]
### Issue

`/contact`

<img width="1908" alt="Screenshot 2024-09-25 at 10 39 22" src="https://github.com/user-attachments/assets/39f851cd-cb71-4840-9c8e-c5222d628de3">

**Comment by amitaibu** [comment]
Yes, thanks

**Comment by sonvir249** [comment]
@amitaibu is this still applicable?
I can see the themed contact form:
![image](https://github.com/user-attachments/assets/0b6cad32-6bea-4896-bf0b-cd70bcc2de5c)

**Comment by amitaibu** [comment]
Yes, it does. 

1. The label and value have weird gaps
2. Emali address is probaly a link, but it doesn't look like it.
3. Checkbox should be next to "Send yourself a copy"

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/5fc43284-163d-448c-98b1-a0c28ed820de">

**Comment by sonvir249** [comment]
@amitaibu raised a PR please review it.
FYI: We should display the email as plain text only, since it's for display purpose. Making it a link would trigger the email app to open.

**Comment by mgurjanov** [comment]
This is done.
