### ISSUE TITLE
Allow $this->markEntityForCleanup to be disabled

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#743]
The `weitzman\DrupalTestTraits\ExistingSiteBase` class uses `$this->markEntityForCleanup` to delete entities after tests. 

It would be handy to have an option to retain these entities for debugging purposes.

Proposed solution:

```xml
<phpunit bootstrap=".bootstrap-fast.php" processIsolation="true">
  <php>

    <env name="DISABLE_MARK_ENTITIES_FOR_CLEANUP" value="TRUE"/>

```

More concise or better names welcome.

**Comment by amitaibu** [comment]
My trick is usually going into the `markEntityForCleanup` method and comment the method's body.

**Comment by mgurjanov** [comment]
I've been using what @amitaibu suggested. Also one from @AronNovak :

```
$html = $this->getSession()->getPage()->getOuterHtml();
file_put_contents('/var/www/html/web/' . md5($html) . '.html', $html);
```

**Comment by bboro** [comment]
You can also just add a `die()` before the end of the test and it will keep the entities btw.

**Comment by mgurjanov** [comment]
Or adding `sleep()`.
