### ISSUE TITLE
Disable TFA by default

### ISSUE THREAD

**Issue by amitaibu** [Gizra/drupal-starter#756]
We should enable 2FA only after going LIVE. We can add a checklist to the README, that includes this info

<img width="423" alt="image" src="https://github.com/user-attachments/assets/9889c89e-647d-4cbe-99c5-8939ecb63b9c">

**Comment by balagan73** [comment]
TFA is only enabled on live by default, so adding above checklist to the README
https://github.com/Gizra/drupal-starter/blob/main/web/sites/default/settings.pantheon.php#L94

**Comment by balagan73** [comment]
Ah, I got it, 'going live', not deploying to live.
