### ISSUE TITLE
Provide server_theme's themes from server_general so it 

### ISSUE THREAD

**Issue by bboro** [Gizra/drupal-starter#83]
Just thought of this as it's been in the back of my mind for a bit.

If we try to render entities in Views module's Preview window just as one example, the entities don't render because the `server-theme-card.html.twig` template cannot be found (for example) when using Claro/Seven. 

This can be resolved if we just `server_theme_theme` (server theme's hook_theme) to `server_general_theme` and copy all the `server-theme-*` templates to be in the module's templates folder. This way in `server_theme` we're overriding templates provided by a module, and since they're provided from a module they should work in any theme such as Seven.

**Comment by amitaibu** [comment]
@bboro thanks, but I think we should keep in the theme. The separation in Drupal between module and themes as already blurry, but normally we'd expect twig files to be in the theme. So I think it's fine to loose the Views preview functionality, for the sake of DX
