### ISSUE TITLE
Kernel Tests are not working

### ISSUE THREAD

**Issue by mariano-dagostino** [Gizra/drupal-starter#98]
```
There was 1 error:

1) Drupal\Tests\server_general\Kernel\ServerGeneralTest::testDummy
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught PHPUnit\Framework\Exception: Could not read "phpunit.xml.dist".
```

**Comment by mariano-dagostino** [comment]
@amitaibu @AronNovak any clue how to make this work? https://travis-ci.com/github/Gizra/drupal-starter/jobs/451446472#L1295

**Comment by mariano-dagostino** [comment]
I'm asking this because we could use drupal-starter to easily run kernel and browser tests when doing some contrib code.

**Comment by amitaibu** [comment]
hmm, I'm was able to run Kernel tests when developing contrib modules.

So I don't know about the travis failure, but what happens when you try to run your contrib module using `ddev phpunit --filter=ClassName`?

**Comment by mariano-dagostino** [comment]
@amitaibu same error:

```bash
> ddev phpunit --filter=ServerGeneralTest
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 400 ms, Memory: 4.00 MB

There was 1 error:

1) Drupal\Tests\server_general\Kernel\ServerGeneralTest::testDummy
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught PHPUnit\Framework\Exception: Could not read "phpunit.xml.dist".

  thrown in /var/www/html/vendor/phpunit/phpunit/src/Util/Configuration.php on line 196
Fatal error: Uncaught PHPUnit\Framework\Exception: Could not read "phpunit.xml.dist".
```

**Comment by amitaibu** [comment]
Are you most up to date `ddev composer install`?

**Comment by mariano-dagostino** [comment]
After configuring properly phpunit.xml from web/core now I'm getting  

```
1) Drupal\Tests\server_general\Kernel\ServerGeneralTest::testDummy
Error: Class 'org\bovigo\vfs\vfsStream' not found
```

Seems related to this https://www.drupal.org/node/2889302

**Comment by mariano-dagostino** [comment]
@amitaibu I tried this again today with a newer version of drupal and now is working out of the box.
